# GoReleaser configuration for claude-ride-with-whip

project_name: claude-ride-with-whip

before:
  hooks:
    - go mod tidy
    - go fmt ./...

builds:
  - id: statusline
    main: ./cmd/statusline
    binary: statusline
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - builds:
      - statusline
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: young1lin
    name: claude-ride-with-whip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

checksum:
  name_template: "checksums.txt"
